name: Lint & Build

on:
  push: {}
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🧪 Run lint
        run: yarn lint

      - name: 🏗️ Run build
        run: yarn build

      - name: 🏷️ Set version
        run: echo ${{ github.sha }} > ./dist/version

      - name: 📤 Publish artifacts
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: artifacts
          publish_dir: ./dist
